; [env:featheresp32-s2]
; platform = espressif32
; board = featheresp32-s2
; framework = arduino
; monitor_speed = 115200

; lib_deps =
;     adafruit/Adafruit MQTT Library
;     adafruit/DHT sensor library
;     adafruit/Adafruit Unified Sensor



[env:d1_mini]
platform = espressif8266
board = d1_mini   ; ESP12E/NodeMCU compatible
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit MQTT Library
    adafruit/Adafruit IO Arduino
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    LiquidCrystal_I2C
