; [env:nodemcuv2]
; platform = espressif8266
; board = nodemcuv2
; framework = arduino

; monitor_speed = 115200

; lib_deps =
;     adafruit/Adafruit IO Arduino @ ^4.2.0
;     adafruit/Adafruit MQTT Library @ ^2.5.9
;     adafruit/Adafruit GFX Library @ ^1.11.7
;     DHT sensor library @ ^1.4.3
;     Adafruit Unified Sensor @ ^1.1.7



[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
  adafruit/Adafruit IO Arduino
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
