[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino

upload_speed = 921600
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit MQTT Library @ ^2.5.0
    LiquidCrystal_I2C
    ESP8266WiFi
    knolleary/PubSubClient@^2.8.0
    adafruit/Adafruit MQTT Library @ ^2.5.0
    ;marco-ron/LiquidCrystal_I2C @ ^1.1.4

