; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino

; upload_speed = 115200
; monitor_speed = 115200

; lib_deps =
;   DHT
;   Robotutor-tech/LCD
;   adafruit/Adafruit MQTT Library@^2.5.8




[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Library Dependencies
; PlatformIO will automatically download these
lib_deps =
    DHT
    Robotutor-tech/LCD
    adafruit/Adafruit MQTT Library@^2.5.8